name: 【功能建议】
description: 改进现有文档或加入新的文档
title: "【功能建议】（在此简单描述新的文档）"
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        ## 请补全标题并认真填写下方内容

  - type: input
    id: enhancement_nav
    attributes:
      label: 模块
      description: 希望加入到导航栏的哪个模块？
      placeholder: 如"误区纠正"或"误区纠正 -> 歧义观点"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 内容描述
      description: 简单概括要加入的内容
    validations:
      required: true

  - type: textarea
    id: document_url
    attributes:
      label: 文档原址
      description: （选填）
      placeholder: 选填，如果有

  - type: textarea
    id: document_info
    attributes:
      label: 重点内容
      description: 填写你认为重要的内容
    validations:
      required: true
