name: 【功能建议】
description: 改进现有文档或加入新的文档
title: "【功能建议】（在此简单描述新的文档）"
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        ## 请补全标题并认真填写下方内容

  - type: input
    id: enhancement_nav
    attributes:
      label: 模块
      description: 希望加入到导航栏的哪个模块？
      placeholder: 如"大众科普"或"误区纠正 -> 歧义观点"
    validations:
      required: true

  - type: input
    id: feature_description
    attributes:
      label: 简述
      description: 简单概括要加入的内容
      placeholder: 如：XX阅读帮助
    validations:
      required: true

  - type: input
    id: document_url
    attributes:
      label: 文档原址
      description: 选填，如果有
      placeholder: 如：https://mgcd.hypercol.com/library/#阅读帮助

  - type: textarea
    id: document_info
    attributes:
      label: 具体内容
      description: 具体描述新增内容，但请注意新增内容的着重点
      placeholder: 在此填写
    validations:
      required: true
